// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0tXSH8BIo4EK0HXRiPXyoflLWxX_X2Vk',
    appId: '1:320222826434:web:5ec2c1179d72ea5c5e105b',
    messagingSenderId: '320222826434',
    projectId: 'ticketavion-fa993',
    authDomain: 'ticketavion-fa993.firebaseapp.com',
    storageBucket: 'ticketavion-fa993.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJVb2Cbk0ROurvm84JZ-V5kr6mKgSU5fE',
    appId: '1:320222826434:android:e68b2d53df6b12a65e105b',
    messagingSenderId: '320222826434',
    projectId: 'ticketavion-fa993',
    storageBucket: 'ticketavion-fa993.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4I3XKFDYmFcX_ZP4sbXErMiCJrqFhbvI',
    appId: '1:320222826434:ios:cd0eea5653f55a405e105b',
    messagingSenderId: '320222826434',
    projectId: 'ticketavion-fa993',
    storageBucket: 'ticketavion-fa993.appspot.com',
    iosBundleId: 'com.example.examenPrograFirebase',
  );
}
